### ISSUE TITLE
Add example of the initial overrided object 

### ISSUE THREAD

**Issue by joeitu** [LinkedSoftwareDependencies/Documentation-Components.js#8]
Hi, 
in the [override doc](https://componentsjs.readthedocs.io/en/latest/configuration/configurations/overrides/) if I understand correctly the first example override an `ex:myHelloWorldWithOverride` object.

Since we don't know what the first object looks like it is hard to tell is part of the original object or what should be directly copied.

For eg. `  "@type": "Override",` 
Is "Override" the type of the initial object or should it be the type when writing an override?

Sorry if this seems a bit confusing, but in short I think an example of the original overridden object would be helpful to make the example clearer.

**Comment by rubensworks** [comment]
Pinging @joachimvh

**Comment by joachimvh** [comment]
Override is a special type to indicate that this object overrides the values of another object. So the original object could look something like:
```json
{
  "@id": "ex:myHelloWorldWithOverride",
  "@type": "hello:HelloWorld",
  "hello:say": "HELLO",
  "hello:hello": "WORLD",
  "hello:punctuation": "!"
}
```

I'll look into updating the example.
